<?php

return ['permissions' => [
    'pos.manage' => 'Use Quick Sale, scan products and record payments',
    'allergies.manage' => 'Manage allergy labels and icons',
    'gallery.manage' => 'Manage gallery events and photos',
    'enquiries.manage' => 'View and manage contact enquiries',
    'settings.manage' => 'Manage general settings and default charges',
    'orders.manage' => 'Manage order status, charges and cash collection',
    'orders.view' => 'View orders and customer details',
    'banners.view' => 'View home banners',
    'banners.manage' => 'Create and edit home banners',
    'dashboard.view' => 'View dashboard',
    'users.view' => 'View users',
    'users.manage' => 'Create, edit and deactivate users',
    'categories.view' => 'View categories',
    'categories.manage' => 'Manage categories',
    'products.view' => 'View complete product catalogue',
    'products.manage' => 'Create, edit and assign products',
    'imports.view' => 'View product import history and source files',
    'imports.manage' => 'Upload and import products',
    'inventory.view' => 'View inventory and stock history',
    'inventory.manage' => 'Adjust product stock',
    'roles.view' => 'View user types',
    'roles.manage' => 'Manage user types and permissions',
]];
