@extends('admin.layout')
@section('title','Payment Report')
@section('content')
<div class="panel"><div class="panel-content">
<p><strong>Online payments: {{ ucfirst(app(\App\Services\GatewayConfiguration::class)->mode()) }}</strong> · @foreach($gateways as $name=>$ready){{ $name }}: {{ $ready?'Configured':'Not configured' }}{{ $loop->last?'':' · ' }}@endforeach</p>
<p>Report uses order dates. Method filters and order counts use the original order method; adjustment receipts/refunds are grouped under the actual method used. Net received excludes processing fees; it is not a bank payout report. Sandbox payments are excluded unless selected.</p>
<form class="mmc-filters" method="get">
<label>From<input class="form-control" type="date" name="from" value="{{ $from }}" required></label>
<label>To<input class="form-control" type="date" name="to" value="{{ $to }}" required></label>
<label>Method<select class="form-control" name="method"><option value="">All methods</option>@foreach(['cash'=>'Cash','card'=>'Card','paypal'=>'PayPal'] as $key=>$label)<option value="{{ $key }}" @selected(request('method')===$key)>{{ $label }}</option>@endforeach</select></label>
<label>Source<select class="form-control" name="source"><option value="">Website & POS</option><option value="website" @selected(request('source')==='website')>Website</option><option value="pos" @selected(request('source')==='pos')>POS</option></select></label>
<label>Payment status<select class="form-control" name="payment_status"><option value="">All statuses</option>@foreach(['unpaid','pending','paid','partially_refunded','refunded'] as $state)<option value="{{ $state }}" @selected(request('payment_status')===$state)>{{ ucfirst(str_replace('_',' ',$state)) }}</option>@endforeach</select></label>
<label><input type="checkbox" name="sandbox" value="1" @checked(request()->boolean('sandbox'))> Include sandbox test payments</label>
<button class="btn btn-primary">Filter</button><a class="btn btn-outline-primary" href="{{ route('admin.reports.payments.export',request()->query()) }}">Export CSV</a>
</form></div></div>
<div class="row">@foreach($summary as $method=>$numbers)<div class="col-md-4"><div class="panel"><div class="panel-content"><h2>{{ $method==='paypal'?'PayPal':ucfirst($method) }}</h2><p>{{ $numbers['count'] }} orders</p><p>Gross received: CAD {{ number_format($numbers['gross']/100,2) }}<br>Refunded: CAD {{ number_format($numbers['refunded']/100,2) }}<br>Unpaid / pending: CAD {{ number_format($numbers['pending']/100,2) }}</p><strong>Net received: CAD {{ number_format(($numbers['gross']-$numbers['refunded'])/100,2) }}</strong></div></div></div>@endforeach</div>
<div class="panel"><div class="panel-content table-responsive"><table class="table"><thead><tr><th>Order / Date</th><th>Source</th><th>Payment</th><th>Status</th><th>Total CAD</th><th>Refunded CAD</th><th>Net received CAD / Balance</th><th>Reference</th></tr></thead><tbody>
@forelse($orders as $order)<tr><td><a href="{{ route('admin.orders.show',$order) }}">{{ $order->number }}</a><small class="d-block">{{ $order->created_at->format('d M Y H:i') }}</small></td><td>{{ ucfirst($order->source) }}</td><td>{{ $order->payment_method==='paypal'?'PayPal':ucfirst($order->payment_method) }}<small class="d-block">{{ $order->payment?->provider ?? ($order->payment_method==='card'?'External terminal':'Manual') }}{{ $order->payment?->mode==='sandbox'?' · SANDBOX':'' }}</small></td><td>{{ ucfirst(str_replace('_',' ',$order->payment_status)) }}</td><td>{{ $order->final_total_cents===null?'Unconfirmed':number_format($order->final_total_cents/100,2) }}</td><td>{{ number_format((($order->payment?->refunded_cents??($order->manual_refunded_cents??($order->payment_status==='refunded'?$order->collected_cents:0)))+abs((int)$order->settlements->where('amount_cents','<',0)->sum('amount_cents')))/100,2) }}</td><td>{{ number_format($order->net_received_cents/100,2) }}<small class="d-block">{{ $order->balance_cents<0?'Refund due':'Amount due' }}: {{ number_format(abs($order->balance_cents)/100,2) }}</small></td><td style="overflow-wrap:anywhere;max-width:230px">{{ $order->payment?->transaction_id ?: '—' }}</td></tr>
@empty<tr><td colspan="7">No matching orders.</td></tr>@endforelse
</tbody></table>{{ $orders->links() }}</div></div>
@endsection
