<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title','Dashboard') | Mamma Mia Admin</title><link rel="icon" href="{{ asset('assets/mmc-favicon.png') }}"><link rel="stylesheet" href="{{ asset('admin-assets/smartadmin/css/vendors.bundle.css') }}"><link rel="stylesheet" href="{{ asset('admin-assets/smartadmin/css/app.bundle.css') }}"><link rel="stylesheet" href="{{ asset('admin-assets/smartadmin/css/fa-solid.css') }}"><link rel="stylesheet" href="{{ asset('admin-assets/mmc-admin.css') }}?v={{ filemtime(public_path('admin-assets/mmc-admin.css')) }}"></head>
<body class="mod-bg-1 mod-nav-link mmc-admin"><div class="page-wrapper"><div class="page-inner"><aside class="page-sidebar"><div class="page-logo"><a href="{{ route('admin.dashboard') }}" class="page-logo-link"><img src="{{ $siteSettings?->logoUrl() ?? asset('logo.png') }}" alt="Mamma Mia Cucina"><span>Mamma Mia <small>ADMINISTRATION</small></span></a></div><nav class="primary-nav"><div class="mmc-sidebar-profile"><strong>{{ auth()->user()->name }}</strong><span>{{ auth()->user()->role->name }}</span></div><ul class="nav-menu"><li class="{{ request()->routeIs('admin.dashboard')?'active':'' }}"><a href="{{ route('admin.dashboard') }}"><i class="fas fa-home" aria-hidden="true"></i><span>Dashboard</span></a></li>
@if(auth()->user()->hasAdminPermission('users.view') || auth()->user()->hasAdminPermission('roles.view'))<li class="nav-title">USER CONTROL</li>@endif
@if(auth()->user()->hasAdminPermission('users.view'))<li class="{{ request()->routeIs('admin.users.*')?'active':'' }}"><a href="{{ route('admin.users.index') }}"><i class="fas fa-users" aria-hidden="true"></i><span>User Management</span></a></li>@endif
@if(auth()->user()->hasAdminPermission('roles.view'))<li class="{{ request()->routeIs('admin.roles.*')?'active':'' }}"><a href="{{ route('admin.roles.index') }}"><i class="fas fa-user-shield" aria-hidden="true"></i><span>User Types & Permissions</span></a></li>@endif
@if(collect(['categories.view','products.view','imports.view','inventory.view'])->contains(fn($permission)=>auth()->user()->hasAdminPermission($permission)))<li class="nav-title">CATALOGUE</li>@endif
@foreach(['products'=>['Manage Products','fa-box-open'],'categories'=>['Categories','fa-tags'],'imports'=>['Product Uploader','fa-file-upload'],'inventory'=>['Inventory','fa-warehouse']] as $module=>$item)
@if(auth()->user()->hasAdminPermission($module.'.view'))<li class="{{ request()->routeIs('admin.'.$module.'.*')?'active':'' }}"><a href="{{ route('admin.'.$module.'.index') }}"><i class="fas {{ $item[1] }}" aria-hidden="true"></i><span>{{ $item[0] }}</span></a></li>@endif
@endforeach
@if(auth()->user()->hasAdminPermission('allergies.manage'))<li class="{{ request()->routeIs('admin.allergies.*')?'active':'' }}"><a href="{{ route('admin.allergies.index') }}"><i class="fas fa-leaf" aria-hidden="true"></i><span>Allergies</span></a></li>@endif
@if(auth()->user()->hasAdminPermission('orders.view'))<li class="{{ request()->routeIs('admin.orders.*')?'active':'' }}"><a href="{{ route('admin.orders.index') }}"><i class="fas fa-shopping-cart" aria-hidden="true"></i><span>Orders</span></a></li>@endif @if(auth()->user()->hasAdminPermission('banners.view') || auth()->user()->hasAdminPermission('settings.manage'))<li class="nav-title">SETTINGS</li>@endif
@if(auth()->user()->hasAdminPermission('banners.view'))
<li class="mmc-admin-home-group"><details class="mmc-admin-submenu" @if(request()->routeIs('admin.banners.*')) open @endif><summary><i class="fas fa-home" aria-hidden="true"></i><span>Home</span><i class="fas fa-chevron-down mmc-submenu-arrow" aria-hidden="true"></i></summary><ul><li class="{{ request()->routeIs('admin.banners.*')?'active':'' }}"><a href="{{ route('admin.banners.index') }}" @if(request()->routeIs('admin.banners.*')) aria-current="page" @endif><i class="fas fa-images" aria-hidden="true"></i><span>Banners</span></a></li></ul></details></li>
@endif

@if(auth()->user()->hasAdminPermission('settings.manage'))<li class="{{ request()->routeIs('admin.settings.*')?'active':'' }}"><a href="{{ route('admin.settings.general') }}"><i class="fas fa-cog" aria-hidden="true"></i><span>General Settings</span></a></li>@endif <li class="nav-title">WEBSITE</li>
@if(auth()->user()->hasAdminPermission('gallery.manage'))<li class="{{ request()->routeIs('admin.gallery.*')?'active':'' }}"><a href="{{ route('admin.gallery.index') }}"><i class="fas fa-images" aria-hidden="true"></i><span>Gallery Events</span></a></li>@endif
@if(auth()->user()->hasAdminPermission('enquiries.manage'))<li class="{{ request()->routeIs('admin.enquiries.*')?'active':'' }}"><a href="{{ route('admin.enquiries.index') }}"><i class="fas fa-envelope" aria-hidden="true"></i><span>Contact Enquiries</span></a></li>@endif
<li><a href="{{ route('theme.index') }}" target="_blank" rel="noopener"><i class="fas fa-external-link-alt" aria-hidden="true"></i><span>View Website</span></a></li></ul></nav></aside><div class="page-content-wrapper"><header class="page-header"><button class="btn btn-outline-primary mr-3 mmc-admin-menu" type="button" aria-label="Toggle sidebar" aria-expanded="false"><i class="fas fa-bars" aria-hidden="true"></i></button><span class="mmc-admin-heading">Mamma Mia Cucina <small>Control Panel</small></span><form class="ml-auto" method="post" action="{{ route('admin.logout') }}">@csrf<button class="btn btn-outline-primary" type="submit">Sign out</button></form></header><main class="page-content"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Admin</a></li><li class="breadcrumb-item active">@yield('title','Dashboard')</li></ol><h1 class="subheader-title mb-4">@yield('title','Dashboard')</h1>@if(session('status'))<div class="alert alert-success" role="status">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger" role="alert"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main><footer class="page-footer"><span>© {{ date('Y') }} Mamma Mia Cucina</span><span class="ml-auto">360 Creative Agency</span></footer></div></div></div><script src="{{ asset('admin-assets/smartadmin/js/vendors.bundle.js') }}"></script><script src="{{ asset('admin-assets/mmc-admin.js') }}?v={{ filemtime(public_path('admin-assets/mmc-admin.js')) }}"></script></body></html>
