<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title','Dashboard') | Mamma Mia Admin</title><link rel="icon" href="{{ asset('assets/mmc-favicon.png') }}"><link rel="stylesheet" href="{{ asset('admin-assets/smartadmin/css/vendors.bundle.css') }}"><link rel="stylesheet" href="{{ asset('admin-assets/smartadmin/css/app.bundle.css') }}"><link rel="stylesheet" href="{{ asset('admin-assets/smartadmin/css/fa-solid.css') }}"><link rel="stylesheet" href="{{ asset('admin-assets/mmc-admin.css') }}?v={{ filemtime(public_path('admin-assets/mmc-admin.css')) }}">
@include('partials.pwa')
</head>
<body class="mod-bg-1 mod-nav-link mmc-admin"><div class="page-wrapper"><div class="page-inner"><aside class="page-sidebar"><div class="page-logo"><a href="{{ route(auth()->user()->isCustomer()?'customer.orders':'admin.dashboard') }}" class="page-logo-link"><img src="{{ $siteSettings?->logoUrl() ?? asset('logo.png') }}" alt="Mamma Mia Cucina"><span>Mamma Mia <small>ADMINISTRATION</small></span></a></div><nav class="primary-nav"><div class="mmc-sidebar-profile"><strong>{{ auth()->user()->name }}</strong><div class="mmc-sidebar-role"><span>{{ auth()->user()->role->name }}</span><a class="mmc-website-shortcut" href="{{ route('theme.index') }}" aria-label="Visit website" title="Visit website"><i class="fas fa-globe" aria-hidden="true"></i></a></div></div><ul class="nav-menu"><li class="{{ request()->routeIs('admin.dashboard')?'active':'' }}"><a href="{{ route(auth()->user()->isCustomer()?'customer.orders':'admin.dashboard') }}"><i class="fas fa-home" aria-hidden="true"></i><span>{{ auth()->user()->isCustomer()?'My Orders':'Dashboard' }}</span></a></li>
@if(auth()->user()->isCustomer())
<li class="{{ request()->routeIs('customer.profile*')?'active':'' }}"><a href="{{ route('customer.profile') }}"><i class="fas fa-user" aria-hidden="true"></i><span>My Profile</span></a></li>
@endif
@include('admin.sidebar-groups')
@if(auth()->user()->hasAdminPermission('banners.view') || auth()->user()->hasAdminPermission('settings.manage') || auth()->user()->hasAdminPermission('gateways.manage') || auth()->user()->hasAdminPermission('about.manage') || auth()->user()->hasAdminPermission('contact.manage') || auth()->user()->hasAdminPermission('catalogue.manage') || auth()->user()->hasAdminPermission('gallery.manage') || auth()->user()->hasAdminPermission('users.view') || auth()->user()->hasAdminPermission('roles.view'))<li class="nav-title">SETTINGS</li>@endif
@if(auth()->user()->hasAdminPermission('banners.view'))
<li class="mmc-admin-home-group"><details class="mmc-admin-submenu" @if(request()->routeIs('admin.banners.*')) open @endif><summary><i class="fas fa-home" aria-hidden="true"></i><span>Home</span><i class="fas fa-chevron-down mmc-submenu-arrow" aria-hidden="true"></i></summary><ul><li class="{{ request()->routeIs('admin.banners.*')?'active':'' }}"><a href="{{ route('admin.banners.index') }}" @if(request()->routeIs('admin.banners.*')) aria-current="page" @endif><i class="fas fa-images" aria-hidden="true"></i><span>Banners</span></a></li></ul></details></li>
@endif

@if(auth()->user()->hasAdminPermission('about.manage'))<li class="{{ request()->routeIs('admin.about.*')?'active':'' }}"><a href="{{ route('admin.about.edit') }}"><i class="fas fa-info-circle" aria-hidden="true"></i><span>About Us</span></a></li>@endif
@if(auth()->user()->hasAdminPermission('catalogue.manage'))<li class="{{ request()->routeIs('admin.catalogue.*')?'active':'' }}"><a href="{{ route('admin.catalogue.index') }}"><i class="fas fa-book-open" aria-hidden="true"></i><span>Catalogue</span></a></li>@endif
@if(auth()->user()->hasAdminPermission('gallery.manage'))<li class="{{ request()->routeIs('admin.gallery.*')?'active':'' }}"><a href="{{ route('admin.gallery.index') }}"><i class="fas fa-images" aria-hidden="true"></i><span>Gallery Events</span></a></li>@endif
@if(auth()->user()->hasAdminPermission('contact.manage'))<li class="{{ request()->routeIs('admin.contact.*')?'active':'' }}"><a href="{{ route('admin.contact.edit') }}"><i class="fas fa-address-book" aria-hidden="true"></i><span>Contact Us</span></a></li>@endif
@if(auth()->user()->hasAdminPermission('settings.manage'))<li class="{{ request()->routeIs('admin.settings.*')?'active':'' }}"><a href="{{ route('admin.settings.general') }}"><i class="fas fa-cog" aria-hidden="true"></i><span>General Settings</span></a></li>@endif @include('admin.sidebar-users')
@if(auth()->user()->hasAdminPermission('settings.manage'))<li class="{{ request()->routeIs('admin.delivery.*')?'active':'' }}"><a href="{{ route('admin.delivery.index') }}"><i class="fas fa-truck" aria-hidden="true"></i><span>Delivery Rates</span></a></li>@endif
@if(auth()->user()->hasAdminPermission('gateways.manage'))<li class="{{ request()->routeIs('admin.gateways.*')?'active':'' }}"><a href="{{ route('admin.gateways.edit') }}"><i class="fas fa-credit-card" aria-hidden="true"></i><span>Gateway Settings</span></a></li>@endif<li class="nav-title">SOCIAL LINKS</li>
@include('admin.sidebar-social')</ul></nav></aside><div class="page-content-wrapper"><header class="page-header"><button class="btn btn-outline-primary mr-3 mmc-admin-menu" type="button" aria-label="Toggle sidebar" aria-expanded="false"><i class="fas fa-bars" aria-hidden="true"></i></button><span class="mmc-admin-heading">Mamma Mia Cucina <small>Control Panel</small></span><form class="ml-auto" method="post" action="{{ route(auth()->user()->isCustomer()?'customer.logout':'admin.logout') }}">@csrf<button class="btn btn-outline-primary" type="submit">Sign out</button></form></header><main class="page-content"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route(auth()->user()->isCustomer()?'customer.orders':'admin.dashboard') }}">Admin</a></li><li class="breadcrumb-item active">@yield('title','Dashboard')</li></ol><h1 class="subheader-title mb-4">@yield('title','Dashboard')</h1>@if(session('status'))<div class="alert alert-success" role="status">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger" role="alert"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main><footer class="page-footer"><span>© {{ date('Y') }} Mamma Mia Cucina</span><span class="ml-auto">360 Creative Agency</span></footer></div></div></div><script src="{{ asset('admin-assets/smartadmin/js/vendors.bundle.js') }}"></script><script src="{{ asset('admin-assets/mmc-admin.js') }}?v={{ filemtime(public_path('admin-assets/mmc-admin.js')) }}"></script><script src="{{ asset('admin-assets/admin-confirm.js') }}?v={{ filemtime(public_path('admin-assets/admin-confirm.js')) }}"></script></body></html>
