@extends('admin.layout')
@section('title','General Settings')
@section('content')
<p><a class="btn btn-outline-primary" href="{{ route('admin.home-sections.edit') }}">Edit Homepage Sections</a></p>
<p><a class="btn btn-outline-primary" href="{{ route('admin.email.history') }}">Email History</a></p>
<div class="panel panel-content"><h2>Email / SMTP Configuration</h2><p>Configure Google Workspace or another SMTP provider for verification and password reset emails.</p><a class="btn btn-outline-primary" href="{{ route('admin.email.edit') }}">Configure Email / SMTP</a></div>
<div class="panel"><div class="panel-container show"><div class="panel-content"><h2>Default Order Charges</h2><p>The flat delivery amount applies when postal-code delivery rates are disabled. Tax is calculated as a percentage of the product subtotal, excluding delivery, and rounded to the nearest cent. Existing orders retain their saved charges; edit an individual order to override them.</p><form enctype="multipart/form-data" method="post" action="{{ route('admin.settings.update') }}">@csrf @method('PUT')<input type="hidden" name="revision" value="{{ $settings->revision }}"><div class="row"><div class="col-md-6"><label for="default-delivery">Delivery amount (CAD)</label><input class="form-control" id="default-delivery" name="delivery" type="number" required min="0" max="9999999.99" step="0.01" value="{{ old('delivery',number_format($settings->delivery_cents/100,2,'.','')) }}"></div><div class="col-md-6"><label for="default-tax">Tax percentage (%)</label><input class="form-control" id="default-tax" name="tax" type="number" required min="0" max="100" step="0.01" value="{{ old('tax',number_format($settings->tax_basis_points/100,2,'.','')) }}"></div></div><p class="mt-3">Enter 0 when no charge applies.</p><hr><h2>Postal-code Delivery Rates</h2><p><a href="{{ route('admin.delivery.index') }}">View matrix, compare services and edit delivery rates →</a></p>
<div class="form-group"><label for="warehouse-postal">Warehouse From postal code</label><input class="form-control" id="warehouse-postal" name="warehouse_postal_code" maxlength="7" value="{{ old('warehouse_postal_code',$settings->warehouse_postal_code ?? 'M2N') }}"><small>Temporary prefix: M2N. Replace with your warehouse postal code.</small></div>
<input type="hidden" name="matrix_delivery_enabled" value="0"><label><input type="checkbox" name="matrix_delivery_enabled" value="1" @checked(old('matrix_delivery_enabled',$settings->matrix_delivery_enabled))> Use postal-code delivery rates at website checkout and Quick Sale</label>
<p>Requires all five service matrices. Unavailable routes are blocked. The flat delivery amount remains in use until this is enabled.</p>
<hr><h2>Pickup Address</h2><label for="pickup-address">Store / warehouse pickup address</label><textarea id="pickup-address" name="pickup_address" class="form-control" rows="3" maxlength="2000">{{ old('pickup_address',$settings->pickup_address) }}</textarea><p>Shown when customers choose Pick up. Set the full address to enable pickup at checkout.</p>
<hr><h2>Website Details</h2>
<div class="form-group"><label for="site-logo">Logo</label><div class="mb-3"><img src="{{ $settings->logoUrl() }}" alt="Current logo" style="width:140px;height:140px;object-fit:contain;background:#1c150a;border-radius:8px;padding:10px"></div><input class="form-control" type="file" id="site-logo" name="logo" accept="image/png,image/jpeg,image/webp"><small class="form-text text-muted">Recommended: transparent PNG, 800 × 800 px. PNG, JPG or WebP, maximum 5 MB. Leave empty to keep the current logo.</small></div>
<div class="form-group"><label for="page-banner">Inner-page banner background</label><div class="mb-3"><img src="{{ $settings->pageBannerUrl() }}" alt="Current page banner" style="width:100%;max-width:600px;height:160px;object-fit:cover"></div><input class="form-control" type="file" id="page-banner" name="page_banner" accept="image/png,image/jpeg,image/webp"><small class="form-text text-muted">Background behind page titles such as General Login, Checkout and About Us. Recommended: wide image, 1920 × 500 px. PNG, JPG or WebP, maximum 5 MB. Leave empty to keep the current background.</small></div>
<p>Contact details, Instagram and Facebook are managed in the Contact Us settings screen.</p>
<div class="form-group"><label for="site-youtube">YouTube video URL or ID</label><input class="form-control" id="site-youtube" name="youtube" value="{{ old('youtube',$settings->youtube_video_id ? 'https://www.youtube.com/watch?v='.$settings->youtube_video_id : '') }}"><small class="form-text text-muted">Paste a YouTube watch, share or Shorts link. Leave empty to hide the video.</small></div>
<hr><h2>Social Links</h2><p>Enter your full profile URLs. Leave a field blank to hide that icon in the footer.</p>
@foreach(['twitter_url'=>'Twitter / X'] as $field=>$label)
<div class="form-group"><label for="{{ $field }}">{{ $label }}</label><input class="form-control" type="url" id="{{ $field }}" name="{{ $field }}" maxlength="500" placeholder="https://" value="{{ old($field,$settings->$field) }}"></div>
@endforeach
<hr><h2>Opening Hours</h2><p>Set the local business hours for each day. Closing before opening indicates an overnight schedule.</p>
@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] as $day)
<div class="row mb-3"><div class="col-md-3"><strong>{{ $day }}</strong><input type="hidden" name="opening_hours[{{ $day }}][closed]" value="0"><label class="d-block"><input type="checkbox" name="opening_hours[{{ $day }}][closed]" value="1" @checked(old('opening_hours.'.$day.'.closed',$settings->opening_hours[$day]['closed'] ?? false))> Closed</label></div><div class="col-md-4"><label for="open-{{ $day }}">Opens</label><input class="form-control" type="time" id="open-{{ $day }}" name="opening_hours[{{ $day }}][open]" required value="{{ old('opening_hours.'.$day.'.open',$settings->opening_hours[$day]['open'] ?? '08:00') }}"></div><div class="col-md-4"><label for="close-{{ $day }}">Closes</label><input class="form-control" type="time" id="close-{{ $day }}" name="opening_hours[{{ $day }}][close]" required value="{{ old('opening_hours.'.$day.'.close',$settings->opening_hours[$day]['close'] ?? '20:30') }}"></div></div>
@endforeach
<button class="btn btn-primary" type="submit">Save Settings</button></form></div></div></div>
@endsection
