<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $order->number }} — Mamma Mia Cucina</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#eee9df;color:#352b20;font:14px/1.55 Arial,sans-serif}.toolbar{max-width:860px;margin:20px auto;display:flex;justify-content:space-between;align-items:center;padding:0 20px;gap:20px}.toolbar button{padding:12px 22px;border:1px solid #b98c43;border-radius:5px;background:#8e0718;color:#fff;cursor:pointer}.sheet{max-width:860px;margin:0 auto 40px;padding:45px;background:white;box-shadow:0 8px 35px #0001}.letterhead{display:flex;align-items:center;gap:28px;border-bottom:3px solid #b98c43;padding-bottom:22px}.letterhead img{width:110px;height:100px;object-fit:contain}.brand{font:30px Georgia,serif;color:#65451e}.tagline,.eyebrow{color:#a17835;letter-spacing:2px;font-size:11px;text-transform:uppercase}.website{font-size:12px;margin-top:7px}.title{display:flex;justify-content:space-between;gap:20px;margin:28px 0}.title h1{font:28px Georgia,serif;margin:4px 0}.meta{text-align:right;font-size:12px;overflow-wrap:anywhere}.details{display:grid;grid-template-columns:1fr 1fr;gap:36px;margin-bottom:28px}.details h2,.notes h2{font:18px Georgia,serif;color:#65451e;border-bottom:1px solid #e5d8bf;padding-bottom:7px}p{margin:8px 0;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse;table-layout:fixed}th{text-align:left;background:#f5efe3;color:#65451e;font-size:11px;text-transform:uppercase;letter-spacing:.5px}td,th{padding:12px 9px;border-bottom:1px solid #e7dfd2;vertical-align:top;overflow-wrap:anywhere}th:nth-child(1){width:48%}th:nth-child(2){width:10%}th:nth-child(3),th:nth-child(4){width:21%}td:nth-child(n+2),th:nth-child(n+2){text-align:right}td small{display:block;color:#86745d;font-size:10px}.totals{margin:20px 0 20px auto;max-width:350px}.totals div{display:flex;justify-content:space-between;gap:18px;padding:8px 0;border-bottom:1px solid #e7dfd2}.totals strong{color:#8e0718}.pending{font-size:12px;color:#756149}.notes p{white-space:pre-wrap}.footer{border-top:2px solid #b98c43;margin-top:32px;padding-top:16px;color:#756149;font-size:12px}.footer strong{font:18px Georgia,serif;color:#65451e}.notes,.totals,.footer{break-inside:avoid}thead{display:table-header-group}tr{break-inside:avoid}
@page{size:A4;margin:16mm} @media print{body{background:#fff;font-size:11px;print-color-adjust:exact;-webkit-print-color-adjust:exact}.toolbar{display:none}.sheet{max-width:none;margin:0;padding:0;box-shadow:none}.letterhead img{width:95px;height:85px}.brand{font-size:26px}.title h1{font-size:25px}td,th{padding:9px 6px}.details{gap:25px}.footer{margin-top:24px}}
@media screen and (max-width:600px){.sheet{padding:22px}.details{grid-template-columns:1fr;gap:10px}.title{display:block}.meta{text-align:left}.brand{font-size:23px}.letterhead{gap:12px}.letterhead img{width:75px}}
</style></head><body><div class="toolbar"><span>Print this document or choose “Save as PDF”.</span><button type="button" onclick="window.print()">Print / Save as PDF</button></div><main class="sheet">
<header class="letterhead"><img src="{{ $siteSettings?->logoUrl() ?? asset('logo.png') }}" alt="Mamma Mia Cucina logo"><div><div class="brand">Mamma Mia Cucina</div><div class="tagline">Italian tradition. Moments to savour.</div><div class="website">mammamiacucina.ca</div></div></header>
<div class="title"><div><div class="eyebrow">Your Italian favourites</div><h1>Order Confirmation</h1></div><div class="meta"><strong>{{ $order->number }}</strong><br>{{ $order->created_at->format('d F Y, H:i') }}<br>Status: {{ $order->status_label }}</div></div>
<div class="details"><section><h2>Customer & Delivery</h2><p><strong>{{ $order->first_name }} {{ $order->last_name }}</strong><br>{{ $order->address }}<br>{{ $order->city }}, {{ $order->province }} {{ $order->postal_code }}<br>{{ $order->country }}</p><p>{{ $order->email }}<br>{{ $order->phone }}</p></section><section><h2>Payment Details</h2><p><strong>Cash on delivery</strong><br>Payment status: {{ ucfirst($order->payment_status) }}<br>Currency: {{ $order->currency }}</p><p class="pending">@if($order->final_total_cents===null)Delivery charges and tax will be confirmed separately before delivery.@endif Cash collection is shown by the payment status above.</p></section></div>
<table><thead><tr><th>Product</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td>{{ $item->name }}@if($item->product_code)<small>Product code: {{ $item->product_code }}</small>@endif @if($item->qr_code)<small>QR code: {{ $item->qr_code }}</small>@endif</td><td>{{ $item->quantity }}</td><td>${{ number_format($item->unit_cents/100,2) }}</td><td>${{ number_format($item->line_cents/100,2) }}</td></tr>@endforeach</tbody></table>
<div class="totals"><div><span>Product subtotal (CAD)</span><strong>${{ number_format($order->subtotal_cents/100,2) }}</strong></div><div><span>Delivery</span><span>{{ $order->delivery_cents===null?'To be confirmed':'$'.number_format($order->delivery_cents/100,2) }}</span></div><div><span>Tax</span><span>{{ $order->tax_cents===null?'To be confirmed':'$'.number_format($order->tax_cents/100,2) }}</span></div></div>
<section class="notes">@if($order->final_total_cents!==null)<p><strong>Final total (CAD): ${{ number_format($order->final_total_cents/100,2) }}</strong></p>@endif<p>Amount due: {{ $order->status==='cancelled'||$order->payment_status==='paid'?'$0.00':($order->final_total_cents===null?'To be confirmed':'$'.number_format($order->final_total_cents/100,2)) }}</p><p>Track your order at mammamiacucina.ca/track-order using order number {{ $order->number }}.</p></section>
@if($order->notes)<section class="notes"><h2>Order Notes</h2><p>{{ $order->notes }}</p></section>@endif
<footer class="footer"><strong>Thank you for choosing Mamma Mia Cucina.</strong><p>A little Italy, a lot of love.<br>Please keep your order number for any enquiries.</p></footer></main></body></html>
