<article class="quote-document">
<header class="quote-brand"><div><img src="{{ $siteSettings?->logoUrl()??asset('logo.png') }}" alt="Mamma Mia Cucina" style="max-width:190px;max-height:80px"><h2>Mamma Mia Cucina</h2></div><div><h1>QUOTATION</h1><strong>{{ $quotation->number }}</strong><p>Issued {{ $quotation->created_at->format('d M Y') }}<br>Valid until {{ $quotation->due_date->format('d M Y') }}</p></div></header>
<section class="quote-client"><small>PREPARED FOR</small><h3>{{ $quotation->customer_snapshot['business_name']?:$quotation->customer_snapshot['name'] }}</h3><p>{{ $quotation->customer_snapshot['name'] }} · Customer #{{ $quotation->customer_id }}<br>{{ $quotation->customer_snapshot['email'] }} · {{ $quotation->customer_snapshot['phone'] }}<br>{{ implode(', ',array_filter(Arr::only($quotation->customer_snapshot,['address','city','province','postal_code','country']))) }}@if($quotation->customer_snapshot['website']??null)<br>{{ $quotation->customer_snapshot['website'] }}@endif</p><p>{{ ucfirst($quotation->pricing_tier) }} pricing · All amounts in CAD</p></section>
<table class="table"><thead><tr><th>Product / Code</th><th>Qty</th><th>Unit</th><th>Discount</th><th>Amount</th></tr></thead><tbody>@foreach($quotation->items as $item)<tr><td><strong>{{ $item['name'] }}</strong><br><small>{{ $item['code'] }}</small></td><td>{{ $item['quantity'] }}</td><td>${{ number_format($item['unit_cents']/100,2) }}</td><td>@if(isset($item['discount_basis_points'])){{ number_format($item['discount_basis_points']/100,2) }}%<br><small>@endif${{ number_format($item['discount_cents']/100,2) }}@if(isset($item['discount_basis_points']))</small>@endif</td><td>${{ number_format($item['total_cents']/100,2) }}</td></tr>@endforeach</tbody></table>
<div class="quote-summary">@foreach(['subtotal_cents'=>'Subtotal','line_discount_cents'=>'Line discounts','discount_cents'=>'Overall discount'.($quotation->discount_basis_points!==null?' ('.number_format($quotation->discount_basis_points/100,2).'%)':''),'charge_cents'=>'Additional charge ('.number_format($quotation->charge_basis_points/100,2).'%)','tax_cents'=>'Tax ('.number_format($quotation->tax_basis_points/100,2).'%)','total_cents'=>'TOTAL CAD'] as $field=>$label)<div class="{{ $field==='total_cents'?'quote-grand':'' }}"><span>{{ $label }}</span><strong>{{ in_array($field,['discount_cents','line_discount_cents'])?'−':'' }}${{ number_format($quotation->$field/100,2) }}</strong></div>@endforeach</div>
@if($quotation->notes)<section class="quote-notes"><h3>Notes & terms</h3><p style="white-space:pre-wrap">{{ $quotation->notes }}</p></section>@endif
<footer>Thank you for considering Mamma Mia Cucina.<br><small>This quotation is not an invoice. Availability is subject to confirmation. Delivery is not included.</small></footer>
</article>
<style>.quote-document{background:#fffdf8;color:#292019;padding:40px;max-width:1000px;margin:auto;font-size:15px}.quote-brand{display:flex;justify-content:space-between;border-bottom:3px solid #ae8539;padding-bottom:20px;gap:20px}.quote-brand h1{color:#940820;letter-spacing:3px}.quote-client{padding:25px 0}.quote-summary{max-width:420px;margin-left:auto}.quote-summary>div{display:flex;justify-content:space-between;padding:9px;gap:20px}.quote-grand{background:#940820;color:white;font-size:20px;margin-top:12px}.quote-notes{border-top:1px solid #dfcaab;margin-top:30px;padding-top:15px}.quote-document footer{margin-top:35px;text-align:center;color:#806944}.quote-document table{width:100%;border-collapse:collapse}.quote-document th,.quote-document td{padding:12px 6px;text-align:left;border-bottom:1px solid #e4d7bf}.quote-document th{background:#f5edde}.quote-document tr{break-inside:avoid}@media print{@page{size:A4;margin:12mm}body{margin:0}.quote-document{padding:0;max-width:none;font-size:11pt}.no-print{display:none!important}.quote-brand img{max-height:55px!important}.quote-grand{print-color-adjust:exact}.quote-summary{break-inside:avoid}thead{display:table-header-group}}</style>
