@extends('admin.layout')
@section('title',$quotation->exists?'Edit Quotation':'Add Quotation')
@section('content')
<form method="post" action="{{ $quotation->exists?route('admin.quotations.update',$quotation):route('admin.quotations.store') }}" id="quote-form" class="panel p-4">@csrf @if($quotation->exists) @method('PUT') @endif
<input type="hidden" name="revision" value="{{ $quotation->revision }}">
<div class="row"><div class="form-group col-md-6"><label>Customer</label><input id="customer-search" class="form-control mb-2" placeholder="Filter by customer ID, name or email"><select id="quote-customer" name="customer_id" class="form-control" required><option value="">Select customer</option>@foreach($customers as $c)<option value="{{ $c['id'] }}" data-tier="{{ $c['tier'] }}" @selected(old('customer_id',$quotation->customer_id)==$c['id'])>#{{ $c['id'] }} — {{ $c['name'] }} ({{ $c['email'] }})</option>@endforeach</select></div>
<div class="form-group col-md-3"><label>Pricing tier</label><select class="form-control" id="quote-tier" name="pricing_tier">@foreach(['auto'=>'Automatic (customer eligibility)','individual'=>'Individual','business'=>'Business (admin override)'] as $v=>$label)<option value="{{ $v }}" @selected(old('pricing_tier',$quotation->pricing_tier??'auto')===$v)>{{ $label }}</option>@endforeach</select><small>Automatic uses business rates only for active, verified and approved business accounts. An override affects this quote only.</small></div>
<div class="form-group col-md-3"><label>Due / valid until</label><input type="date" class="form-control" name="due_date" value="{{ old('due_date',$quotation->due_date?->format('Y-m-d')??now()->addDays(30)->format('Y-m-d')) }}" required></div></div>
<p>All active products load when you select a customer. Remove unwanted rows. Quote prices are editable for this quotation only. Sale-unit and carton prices are linked using pieces per carton; quantity counts cartons. Products without a known pack size show no sale-unit price. Changing customer or pricing tier reloads the standard prices.</p>
<div class="d-flex flex-wrap mb-3"><input id="product-filter" class="form-control mr-2" style="max-width:350px" placeholder="Find product by name, code or number"><button type="button" id="remove-selected" class="btn btn-outline-danger mr-2">Remove checked</button><button type="button" id="restore-products" class="btn btn-outline-primary">Add missing products</button></div>
<details class="quote-column-picker mb-3"><summary class="btn btn-outline-primary">Choose columns</summary>
<div class="p-3"><p class="text-muted">Product details are read-only. Choose which details to show alongside the quotation fields.</p>
<div class="d-flex flex-wrap mb-3" style="gap:8px">@foreach($columnPresets as $label=>$keys)<button type="button" class="btn btn-outline-primary quote-column-preset" data-columns="{{ implode(',',$keys) }}">{{ $label }}</button>@endforeach<button type="button" class="btn btn-outline-primary quote-column-preset" data-columns="{{ implode(',',array_keys($columnLabels)) }}">All columns</button><button type="button" class="btn btn-outline-primary quote-column-preset" data-columns="">Clear selection</button></div>
<div class="quote-column-options">@foreach($columnLabels as $key=>$label)<label><input type="checkbox" class="quote-column-toggle" value="{{ $key }}"> {{ $label }}</label>@endforeach</div></div></details>
<div class="table-responsive quote-table-wrap"><table class="table quote-table"><thead><tr id="quote-head"></tr></thead><tbody id="quote-items"></tbody></table></div>
<style>.quote-column-picker{border:1px solid #dfcaab;border-radius:8px;padding:12px}.quote-column-options{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px}.quote-column-options label{margin:0}.quote-table-wrap{max-width:100%;max-height:72vh;overflow:auto}.quote-table{margin:0}.quote-table thead th{background:#3d241b!important;color:#fff!important;white-space:nowrap;position:sticky;top:0;z-index:1}.quote-table .quote-category th{background:#eee4d4;color:#3d241b;text-transform:uppercase;font-weight:700;padding:9px 12px}.quote-table .quote-product:nth-child(even){background:#f8f3eb}.quote-table td{vertical-align:middle}.quote-table .quote-name{min-width:210px}.quote-table .quote-detail{min-width:145px;max-width:320px;overflow-wrap:anywhere}.quote-table .quote-detail img{width:52px;height:52px;object-fit:contain}.quote-table .line-total{white-space:nowrap;font-weight:600}.quote-table input[type=number]{min-width:115px}.quote-table input[data-field=quantity],.quote-table input[data-field=discount_percent]{min-width:85px}</style>
<div class="row">@foreach(['discount_percent'=>'Overall discount (%)','charge_percent'=>'Additional charge (%)','tax_percent'=>'Tax (%)'] as $field=>$label)<div class="form-group col-md-4"><label>{{ $label }}</label><input class="form-control quote-adjustment" id="{{ $field }}" name="{{ $field }}" type="number" min="0" step="0.01" max="100" value="{{ old($field,$field==='discount_percent'?($quotation->discount_basis_points!==null?$quotation->discount_basis_points/100:round(($quotation->discount_cents??0)*100/max(1,($quotation->subtotal_cents??0)-($quotation->line_discount_cents??0)),2)):($field==='charge_percent'?($quotation->charge_basis_points??0)/100:($quotation->tax_basis_points??$tax)/100)) }}" required></div>@endforeach</div>
<p class="text-muted">Line discounts and overall discount are deducted first. The percentage charge applies next, and tax applies to that amount. Delivery is not included.</p>
@if($quotation->exists && $quotation->discount_basis_points===null)<p class="text-muted">This older quotation used fixed discounts. Editing converts them to percentages; review the recalculated totals before saving.</p>@endif
<section id="quote-totals" class="quotation-totals" aria-live="polite"><h2>Quotation summary</h2>
@foreach(['subtotal'=>'Product subtotal','line-discounts'=>'Line discounts','discount'=>'Overall discount','charge'=>'Additional charge','tax'=>'Tax','total'=>'Total amount'] as $key=>$label)<div class="{{ $key==='total'?'quotation-total-final':'' }}"><span>{{ $label }} <small id="summary-{{ $key }}-rate"></small></span><strong id="summary-{{ $key }}">$0.00</strong></div>@endforeach
<small class="quotation-currency">All amounts in CAD</small></section>
<style>.quotation-totals{max-width:480px;margin:24px 0 28px auto;border:1px solid #d9bd86;border-radius:8px;padding:24px;background:#fffaf0;color:#49331e}.quotation-totals h2{font-family:Georgia,serif;font-size:25px;margin:0 0 16px}.quotation-totals>div{display:flex;justify-content:space-between;gap:18px;padding:10px 0}.quotation-totals strong{white-space:nowrap;font-variant-numeric:tabular-nums}.quotation-totals small{color:#806944}.quotation-totals .quotation-total-final{border-top:1px solid #d9bd86;margin-top:12px;padding-top:18px;font-size:22px;color:#970b22}.quotation-currency{display:block;text-align:right;margin-top:6px}</style>
<div class="form-group"><label>Notes / terms</label><textarea class="form-control" name="notes" maxlength="5000" rows="3">{{ old('notes',$quotation->notes) }}</textarea></div><button class="btn btn-primary" id="save-quote">Save quotation</button> <a href="{{ route('admin.quotations.index') }}" class="btn btn-outline-primary">Cancel</a>
</form>
<script type="application/json" id="quotation-data">{!! json_encode(['products'=>$products,'items'=>old('items',$quotation->items),'saved'=>$quotation->items,'customer'=>$quotation->customer_id,'tier'=>$quotation->pricing_tier,'columnLabels'=>$columnLabels],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>
<script src="{{ asset('admin-assets/quotations.js') }}?v={{ filemtime(public_path('admin-assets/quotations.js')) }}"></script>
@endsection
