@extends('admin.layout')
@section('title','Order '.$order->number)
@section('content')
<div class="customer-order-actions"><a href="{{ route('customer.orders') }}">← My Orders</a><a class="btn btn-outline-primary" href="{{ route('customer.order.print',$order) }}" target="_blank" rel="noopener">Print / Save PDF</a></div>
@include('partials.transfer-receipt')
<article class="customer-receipt">
<header class="customer-receipt-brand"><img src="{{ $siteSettings?->logoUrl() ?? asset('logo.png') }}" alt="Mamma Mia Cucina"><div><h2>Mamma Mia Cucina</h2><p>ITALIAN TRADITION. MOMENTS TO SAVOUR.</p><small>mammamiacucina.ca</small></div></header>
<div class="customer-receipt-title"><div><p class="receipt-eyebrow">YOUR ITALIAN FAVOURITES</p><h2>Order Confirmation</h2></div><div class="receipt-meta"><strong>{{ $order->number }}</strong><span>{{ $order->created_at->format('d F Y, H:i') }}</span><span class="receipt-status">{{ $order->status_label }}</span></div></div>
<div class="customer-receipt-details"><section><h3>Customer & {{ $order->fulfillment==='pickup'?'Pick up':'Delivery' }}</h3><strong>{{ $order->first_name }} {{ $order->last_name }}</strong>@if($order->fulfillment!=='pickup')<address>{{ $order->address }}<br>{{ $order->city }}, {{ $order->province }} {{ $order->postal_code }}<br>{{ $order->country }}</address>@endif<p>{{ $order->email }}<br>{{ $order->phone }}</p></section><section><h3>Payment Details</h3><strong>{{ $order->payment_label }}</strong><p>Payment status: {{ ucfirst(str_replace('_',' ',$order->payment_status)) }}<br>Currency: CAD</p><p class="receipt-muted">Payment collection is shown by the payment status above.</p></section></div>
<div class="receipt-table-wrap"><table><thead><tr><th>Product</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td>{{ $item->name }}</td><td>{{ $item->quantity }}</td><td>${{ number_format($item->unit_cents/100,2) }}</td><td>${{ number_format($item->line_cents/100,2) }}</td></tr>@endforeach</tbody></table></div>
@if($order->fulfillment === 'pickup' && $order->pickup_address)<p style="white-space:pre-line"><strong>Pickup address</strong><br>{{ $order->pickup_address }}</p>@endif
@include('partials.order-delivery')
<div class="receipt-totals"><div><span>Subtotal</span><strong>${{ number_format($order->subtotal_cents/100,2) }}</strong></div><div><span>{{ $order->fulfillment==='pickup'?'Pick up':'Delivery' }} @if($order->delivery_service) · {{ ucwords(str_replace("_", " ", $order->delivery_service)) }}@endif</span><span>{{ $order->delivery_cents===null?'To be confirmed':'$'.number_format($order->delivery_cents/100,2) }}</span></div><div><span>Tax</span><span>{{ $order->tax_cents===null?'To be confirmed':'$'.number_format($order->tax_cents/100,2) }}</span></div><div class="receipt-grand-total"><strong>Total (CAD)</strong><strong>{{ $order->final_total_cents===null?'To be confirmed':'$'.number_format($order->final_total_cents/100,2) }}</strong></div>@if($order->final_total_cents!==null)<div><span>{{ $order->balance_cents<0?'Refund due':'Amount due' }}</span><strong>${{ number_format(abs($order->balance_cents)/100,2) }}</strong></div>@endif</div>
@if($order->notes)<section class="receipt-notes"><h3>Order Notes</h3><p>{{ $order->notes }}</p></section>@endif
<footer class="customer-receipt-footer"><h3>Thank you for choosing Mamma Mia Cucina.</h3><p>A little Italy, a lot of love.<br>Please keep your order number for any enquiries.</p></footer>
</article>
@endsection
