<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Catalogue | Mamma Mia Cucina</title><link rel="stylesheet" href="{{ asset("assets/css/mmc-flipbook.css") }}?v={{ filemtime(public_path("assets/css/mmc-flipbook.css")) }}"></head><body>
<div class="app" id="app">
<header><div class="brand" aria-label="Mamma Mia Cucina">MAMMA MIA<small>CUCINA</small></div><div class="tools"><span class="header-label">THE CATALOGUE</span><button class="tool" id="categories-button" aria-label="Browse categories" title="Browse categories"><svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></svg><span>Categories</span></button><button class="tool" id="pages-button" aria-label="Browse all pages" title="Browse all pages"><svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg><span>All Pages</span></button><button class="tool" id="zoom-button" aria-label="Zoom into page" title="Zoom into page"><svg viewBox="0 0 24 24"><circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6M10 7v6M7 10h6"/></svg><span>Zoom</span></button><button class="tool" id="fullscreen" aria-label="Enter full screen" title="Full screen"><svg viewBox="0 0 24 24"><path d="M3 9V3h6M15 3h6v6M21 15v6h-6M9 21H3v-6"/></svg></button></div></header>
<main class="stage" id="stage" aria-label="Interactive catalogue"><button class="side-nav prev" id="previous" aria-label="Previous pages"><svg viewBox="0 0 24 24"><path d="m15 5-7 7 7 7"/></svg></button><div class="book" id="book"></div><button class="side-nav next" id="next" aria-label="Next pages"><svg viewBox="0 0 24 24"><path d="m9 5 7 7-7 7"/></svg></button><div class="status" id="hint">Turn the pages. Select a page to look closer.</div><div id="loading" class="loading">Opening the catalogue...</div></main>
<footer><span class="footer-label">IMPORTED FROM ITALY</span><input type="range" id="progress" class="progress" min="1" max="{{ $catalogue["count"] }}" value="1" aria-label="Go to catalogue page"><div class="pager"><button id="first" aria-label="First page" title="First page"><svg viewBox="0 0 24 24"><path d="M5 5v14m12-14-7 7 7 7"/></svg></button><label for="page-input" class="sr-only">Page number</label><input id="page-input" type="number" inputmode="numeric" min="1" max="{{ $catalogue["count"] }}" value="1"><span id="page-tail">/ {{ $catalogue["count"] }}</span><button id="last" aria-label="Last page" title="Last page"><svg viewBox="0 0 24 24"><path d="M19 5v14M7 5l7 7-7 7"/></svg></button></div></footer>
</div>
<div class="scrim" id="scrim" hidden></div><section class="drawer" id="drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title" hidden><div class="panel-head"><h2 id="drawer-title">Browse Catalogue</h2><button id="close-drawer" class="close" aria-label="Close page browser"><svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg></button></div><div class="panel-tabs" role="tablist" aria-label="Catalogue navigation"><button id="categories-tab" role="tab" aria-selected="true" aria-controls="categories-panel">Categories</button><button id="all-pages-tab" role="tab" aria-selected="false" aria-controls="thumbs">All Pages</button></div><div class="nav-content" id="categories-panel" role="tabpanel" aria-labelledby="categories-tab"><p class="nav-group-label">Catalogue sections</p><nav class="category-list" id="category-list" aria-label="Product categories"></nav><p class="panel-note">{{ $catalogue["count"] }} pages. Select a collection to go to its opening page.</p></div><div class="thumbs" id="thumbs" role="tabpanel" aria-labelledby="all-pages-tab" hidden></div></section>
<section class="zoom-dialog" id="zoom" role="dialog" aria-modal="true" aria-labelledby="zoom-label" hidden><div class="zoom-toolbar"><span class="zoom-label" id="zoom-label">Page 1</span><div class="tools"><button id="zoom-out" aria-label="Zoom out"><svg viewBox="0 0 24 24"><path d="M5 12h14"/></svg></button><output id="zoom-level">100%</output><button id="zoom-in" aria-label="Zoom in"><svg viewBox="0 0 24 24"><path d="M5 12h14M12 5v14"/></svg></button><button id="zoom-fit" title="Fit page" aria-label="Fit page"><svg viewBox="0 0 24 24"><path d="M3 9V3h6M15 3h6v6M21 15v6h-6M9 21H3v-6"/></svg></button><button id="close-zoom" aria-label="Close zoom"><svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg></button></div></div><div class="zoom-scroll" id="zoom-scroll"><div class="zoom-inner"><img id="zoom-image" class="zoom-image" alt=""></div></div><div class="zoom-help">Use + and - to zoom. Drag or scroll to explore.</div></section>
<div class="sr-only" role="status" aria-live="polite" id="announcement"></div>
<noscript>Please enable JavaScript in your browser to turn the catalogue pages.</noscript>

<script>window.MMC_FLIPBOOK = {{ Illuminate\Support\Js::from($catalogue) }};</script><script src="{{ asset("assets/js/mmc-flipbook.js") }}?v={{ filemtime(public_path("assets/js/mmc-flipbook.js")) }}"></script></body></html>
