@extends('layouts.mmc-page', ['pageTitle'=>'Checkout'])
@section('page-content')
<nav class="mmc-shopping-steps"><a href="{{ route('theme.cart') }}">01 · Cart</a><strong>02 · Checkout</strong><span>03 · Confirmation</span></nav>
@if($errors->any())<div class="mmc-panel" role="alert"><p>Please check the following:</p><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul><a href="{{ route('theme.cart') }}">Review your cart</a></div>@endif
<form class="mmc-cart-layout mmc-form" method="post" action="{{ route('checkout.store') }}" data-place-order>
@csrf<input type="hidden" name="checkout_token" value="{{ $token }}">
<section class="mmc-panel"><h2>Customer & Delivery Details</h2><div class="mmc-form-grid">
@foreach(['first_name'=>['First name','given-name',100],'last_name'=>['Last name','family-name',100],'email'=>['Email address','email',255],'phone'=>['Phone number','tel',40],'address'=>['Street address','street-address',255],'city'=>['City','address-level2',100],'province'=>['Province / State','address-level1',100],'postal_code'=>['Postal code','postal-code',30],'country'=>['Country','country-name',100]] as $key=>$field)
<div><label for="checkout-{{ $key }}">{{ $field[0] }}</label><input class="form-control" id="checkout-{{ $key }}" name="{{ $key }}" type="{{ $key==='email'?'email':($key==='phone'?'tel':'text') }}" autocomplete="{{ $field[1] }}" maxlength="{{ $field[2] }}" value="{{ old($key,$key==='country'?'Canada':'') }}" required @error($key) aria-invalid="true" @enderror></div>
@endforeach</div><label for="order-notes">Order notes (optional)</label><textarea class="form-control" id="order-notes" name="notes" maxlength="2000" rows="3">{{ old('notes') }}</textarea></section>
<aside class="mmc-panel mmc-checkout-summary"><p class="mmc-eyebrow">ORDER SUMMARY</p><h2>Your Order</h2><div class="mmc-checkout-items">@foreach($cart['items'] as $item)<div class="mmc-checkout-item"><span>{{ $item['product']->premium_marketing_name }}<small>Quantity: {{ $item['quantity'] }}</small></span><strong>${{ number_format($item['line_cents']/100,2) }}</strong></div>@endforeach</div>
<div class="mmc-checkout-charges"><div class="mmc-checkout-subtotal"><strong>Product subtotal <small>(CAD)</small></strong><strong>${{ number_format($cart['total']/100,2) }}</strong></div><div><span>Delivery</span><span>${{ number_format($charges['delivery']/100,2) }}</span></div><div><span>Tax ({{ rtrim(rtrim(number_format($charges['rate']/100,2),'0'),'.') }}%)</span><span>${{ number_format($charges['tax']/100,2) }}</span></div></div>
<div class="mmc-checkout-total"><div><strong>Total amount</strong><small>CAD · Includes delivery and tax</small></div><strong>${{ number_format(($cart['total']+$charges['delivery']+$charges['tax'])/100,2) }}</strong></div>
<div class="mmc-checkout-payment"><span class="mmc-payment-dot" aria-hidden="true"></span><div><strong>Cash on delivery</strong><p>Pay in cash when you receive your order.</p></div></div><button class="mmc-button" type="submit">Place Order</button></aside></form>
@endsection
