@extends('admin.layout')
@section('title','Customer #'.$customer->id)
@section('content')
@if(auth()->user()->hasAdminPermission('users.manage'))<a class="btn btn-primary mb-4" href="{{ route('admin.customers.edit',$customer) }}">Edit Customer / Account Access</a>@endif
<a class="btn btn-outline-primary mb-4" href="{{ route('admin.customers.index') }}">Back to Customers</a>
<div class="panel panel-content"><div class="row"><div class="col-md-6"><h2>{{ $customer->name }}</h2><p>{{ $customer->email }}<br>{{ $customer->phone }}</p><p>{{ $customer->account_type==='business'?'Business owner':'Individual' }} · {{ $customer->user->is_active?'Active':'Inactive' }}<br>Email: {{ $customer->user->email_verified_at?'Verified':'Awaiting verification' }}<br>Registered: {{ $customer->created_at->format('d M Y') }}</p></div><div class="col-md-6"><h3>{{ $customer->orders_count }} orders placed</h3><h4>Latest order address</h4>@if($latestOrder)<p>{{ $latestOrder->first_name }} {{ $latestOrder->last_name }}<br>{{ $latestOrder->address }}<br>{{ $latestOrder->city }}, {{ $latestOrder->province }} {{ $latestOrder->postal_code }}<br>{{ $latestOrder->country }}</p>@else<p>No order address yet.</p>@endif</div></div></div>
@if($customer->account_type==='business')<div class="panel panel-content"><h2>Business details</h2><dl>@foreach(['business_bin'=>'BIN number','business_name'=>'Business name','business_phone'=>'Business contact number','business_email'=>'Business email'] as $field=>$label)<dt>{{ $label }}</dt><dd>{{ $customer->$field ?: 'Not provided' }}</dd>@endforeach</dl></div>@endif
<div class="panel panel-content"><h2>Order History</h2><div class="table-responsive"><table class="table"><thead><tr><th>Order</th><th>Date</th><th>Source</th><th>Status</th><th>Payment</th><th>Total CAD</th><th>Action</th></tr></thead><tbody>
@forelse($orders as $order)<tr><td>{{ $order->number }}</td><td>{{ $order->created_at->format('d M Y H:i') }}</td><td>{{ ucfirst($order->source) }}</td><td>{{ $order->status_label }}</td><td>{{ ucfirst($order->payment_status) }}</td><td>{{ $order->final_total_cents===null?'Pending':number_format($order->final_total_cents/100,2) }}</td><td><a class="btn btn-outline-primary" href="{{ route('admin.orders.show',$order) }}">View order</a></td></tr>@empty<tr><td colspan="7">No orders placed yet.</td></tr>@endforelse
</tbody></table></div>{{ $orders->links() }}</div>
@endsection
