@extends('admin.layout')
@section('title',$banner->exists?'Edit Banner':'Add Banner')
@section('content')
<a class="btn btn-outline-primary mb-3" href="{{ route('admin.banners.index') }}">← Back to Banners</a>
<form method="post" enctype="multipart/form-data" action="{{ $banner->exists?route('admin.banners.update',$banner):route('admin.banners.store') }}">@csrf @if($banner->exists)@method('PUT')@endif
<div class="panel"><div class="panel-hdr"><h2>Banner Image & Content</h2></div><div class="panel-container show"><div class="panel-content">
@if($banner->exists)<img src="{{ $banner->image_url }}" alt="{{ $banner->alt_text }}" style="display:block;width:100%;max-width:850px;aspect-ratio:2129/739;object-fit:contain;margin-bottom:20px">@endif
<div class="form-group"><label for="image">Banner image</label><input id="image" name="image" class="form-control" type="file" accept="image/jpeg,image/png,image/webp" @required(!$banner->exists)><small class="form-text text-muted"><strong>Recommended: 2129 × 739 px</strong> (wide landscape). JPG, PNG or WebP; maximum 10 MB. Leave the centre clear for text. @if($banner->exists)Leave empty to keep the current image.@endif</small></div>
<div class="row"><div class="form-group col-md-6"><label for="heading">Heading</label><textarea class="form-control" id="heading" name="heading" rows="2" maxlength="160" required>{{ old('heading',$banner->heading) }}</textarea><small class="text-muted">Use Enter for a line break, ideally two short lines.</small></div><div class="form-group col-md-6"><label for="subheading">Subheading</label><input class="form-control" id="subheading" name="subheading" maxlength="255" value="{{ old('subheading',$banner->subheading) }}" required></div>
<div class="form-group col-md-6"><label for="button_text">Button text</label><input class="form-control" id="button_text" name="button_text" maxlength="80" value="{{ old('button_text',$banner->button_text) }}" required><small class="text-muted">Always links directly to the product grid.</small></div><div class="form-group col-md-6"><label for="alt_text">Image description</label><input class="form-control" id="alt_text" name="alt_text" maxlength="255" value="{{ old('alt_text',$banner->alt_text) }}" required></div>
<div class="form-group col-md-6"><label for="priority">Priority</label><input class="form-control" type="number" min="1" max="100000" id="priority" name="priority" value="{{ old('priority',$banner->priority) }}" required><small class="text-muted">1 appears first. Lower numbers appear earlier.</small></div><div class="form-group col-md-6"><label for="is_active">Status</label><select class="form-control" id="is_active" name="is_active"><option value="1" @selected(old('is_active',$banner->is_active)==1)>Active</option><option value="0" @selected(old('is_active',$banner->is_active)==0)>Inactive</option></select></div></div>
<button class="btn btn-primary">Save Banner</button></div></div></div></form>
@endsection
