@if(auth()->user()->hasAdminPermission('orders.manage'))
<div class="panel"><div class="panel-content"><h2>Payments & adjustments</h2><p>Received (after refunds): <strong>CAD {{ number_format($order->net_received_cents/100,2) }}</strong> · Current order total: CAD {{ number_format(($order->final_total_cents??0)/100,2) }}</p>
@if($order->balance_cents!==0 && $order->final_total_cents!==null && ($order->status!=='cancelled' || $order->balance_cents<0) && (!$order->payment || ($order->payment->paid_at && !$order->payment->attention)))
<p class="text-danger"><strong>{{ $order->balance_cents>0?'Amount due':'Refund due' }}: CAD {{ number_format(abs($order->balance_cents)/100,2) }}</strong></p>
<p>Record money only after it has actually been collected or returned. This form does not charge or refund Stripe/PayPal. For a refund of the original online payment, use the provider dashboard and Reconcile (PayPal partial refunds require its refund webhook); this form can refund separately collected payments.</p>
<form method="post" action="{{ route('admin.orders.settlement',$order) }}">@csrf<input type="hidden" name="revision" value="{{ $order->revision }}"><input type="hidden" name="direction" value="{{ $order->balance_cents>0?'collect':'refund' }}"><div class="row"><label class="col-md-4">Amount (CAD)<input class="form-control" type="number" step="0.01" min="0.01" max="{{ number_format(abs($order->balance_cents)/100,2,'.','') }}" name="amount" required></label><label class="col-md-4">Method<select class="form-control" name="method"><option value="cash">Cash</option><option value="card">Card / external terminal</option><option value="paypal">PayPal / external transaction</option></select></label><label class="col-md-4">Transaction reference (required except cash)<input class="form-control" name="reference" maxlength="255"></label></div><label>Note<textarea class="form-control" name="note" required maxlength="1000"></textarea></label><p><label><input type="checkbox" name="received" value="1" required> I confirm this money has already been collected / returned.</label></p><button class="btn btn-primary">Record {{ $order->balance_cents>0?'collection':'refund' }}</button></form>
@endif
@foreach($order->settlements as $entry)<p>{{ $entry->created_at->format('d M Y H:i') }} · {{ $entry->amount_cents>0?'Collected':'Refunded' }} CAD {{ number_format(abs($entry->amount_cents)/100,2) }} · {{ ucfirst($entry->method) }} · {{ $entry->reference }} · {{ $entry->note }}</p>@endforeach
</div></div>
@endif
