@extends('admin.layout')
@section('title','Order '.$order->number)
@section('content')
<p><a class="btn btn-outline-primary" href="{{ route('admin.orders.index') }}">← Back to Orders</a> <a class="btn btn-primary" href="{{ route('admin.orders.print',$order) }}" target="_blank" rel="noopener">Print / Save as PDF</a></p>
<div class="panel"><div class="panel-container show"><div class="panel-content"><p>Placed {{ $order->created_at->format('d M Y H:i') }} · {{ $order->status_label }}</p><h2>Customer & Delivery</h2><p>{{ $order->first_name }} {{ $order->last_name }}<br>{{ $order->email }}<br>{{ $order->phone }}</p><p>{{ $order->address }}<br>{{ $order->city }}, {{ $order->province }} {{ $order->postal_code }}<br>{{ $order->country }}</p>@if($order->notes)<h3>Order notes</h3><p style="white-space:pre-wrap">{{ $order->notes }}</p>@endif<h2>Products</h2>@include('partials.order-lines')</div></div></div>
@if(auth()->user()->hasAdminPermission('orders.manage'))
<div class="panel"><div class="panel-container show"><div class="panel-content"><h2>Manage Order</h2><form method="post" action="{{ route('admin.orders.update',$order) }}">@csrf @method('PATCH')<input type="hidden" name="revision" value="{{ $order->revision }}">
<div class="row"><div class="col-md-6"><label>Status</label><select class="form-control" name="status">@foreach(\App\Models\Order::STATUSES as $key=>$label)<option value="{{ $key }}" @selected(old('status',$order->status)===$key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-6"><label>Cash payment</label><select class="form-control" name="payment_status">@foreach(['unpaid'=>'Unpaid','paid'=>'Paid — cash received','refunded'=>'Refunded — cash returned (cancellation)'] as $key=>$label)<option value="{{ $key }}" @selected(old('payment_status',$order->payment_status)===$key)>{{ $label }}</option>@endforeach</select></div></div>
<div class="row mt-3"><div class="col-md-6"><label>Delivery charge (CAD)</label><input class="form-control" type="number" min="0" max="9999999.99" step="0.01" name="delivery" value="{{ old('delivery',$order->delivery_cents===null?'':number_format($order->delivery_cents/100,2,'.','')) }}"></div><div class="col-md-6"><label>Tax amount (CAD)</label><input class="form-control" type="number" min="0" max="9999999.99" step="0.01" name="tax" value="{{ old('tax',$order->tax_cents===null?'':number_format($order->tax_cents/100,2,'.','')) }}"></div></div><p class="mt-2">Leave charges blank until confirmed; enter 0 for no charge. Mark Paid only after cash is received. Cancellation restores deducted stock once. Return collected cash before cancelling a paid order.</p><label>Internal change note (optional)</label><textarea class="form-control" name="reason" maxlength="1000">{{ old('reason') }}</textarea><button class="btn btn-primary mt-3" type="submit">Save Order</button></form></div></div></div>
@endif
<div class="panel"><div class="panel-container show"><div class="panel-content"><h2>Order History</h2>@forelse($order->events as $event)<p><strong>{{ $event->created_at->format('d M Y H:i') }} · {{ $event->author?->name ?? 'System' }}</strong><br>{{ $event->description }}</p>@empty<p>No changes recorded yet.</p>@endforelse</div></div></div>
@endsection
