@extends('admin.layout')
@section('title','Manage Products')
@section('content')
<div class="mmc-toolbar"><p>{{ $products->total() }} products · All imported details are available under View.</p>@if(auth()->user()->hasAdminPermission('products.manage'))<a class="btn btn-primary" href="{{ route('admin.products.create') }}">Add Product</a>@endif</div>
<form class="mmc-filters" method="get"><label>Search<input class="form-control" name="q" value="{{ request('q') }}" placeholder="Name, barcode, QR code, product code or supplier"></label><label>Category<select class="form-control" name="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('category')==$category->id)>{{ $category->name }}</option>@endforeach</select></label><label>Status<select class="form-control" name="active"><option value="">All statuses</option><option value="1" @selected(request('active')==='1')>Active</option><option value="0" @selected(request('active')==='0')>Inactive</option></select></label><button class="btn btn-primary">Filter</button><a href="{{ route('admin.products.index') }}">Reset</a></form>
<form method="post" action="{{ route('admin.products.bulk-category') }}">@csrf
<div class="panel"><div class="panel-container show"><div class="panel-content table-responsive"><table class="table"><thead><tr>@if(auth()->user()->hasAdminPermission('products.manage'))<th><input type="checkbox" data-select-products aria-label="Select all products on this page"></th>@endif<th>Product</th><th>Supplier / Code</th><th>Categories</th><th>Selling price (CAD)</th><th>Status</th><th></th></tr></thead><tbody>@forelse($products as $product)<tr>@if(auth()->user()->hasAdminPermission('products.manage'))<td><input type="checkbox" name="product_ids[]" value="{{ $product->id }}" aria-label="Select {{ $product->premium_marketing_name }}"></td>@endif<td><div class="mmc-product-cell">@if($thumbnail=$product->media->first())<img class="mmc-product-thumbnail" src="{{ route('admin.products.media',[$product,$thumbnail]) }}" alt="{{ $product->premium_marketing_name }}" width="64" height="64" loading="lazy">@else<span class="mmc-product-thumbnail mmc-product-thumbnail--empty">No image</span>@endif<div><strong>{{ $product->premium_marketing_name }}</strong><small class="d-block">QR: {{ $product->qr_code }}</small><small class="d-block">Barcode: {{ $product->barcode_number }}</small><a class="btn btn-sm btn-outline-primary mt-2" target="_blank" rel="noopener" href="{{ route('admin.products.labels', ['product_ids'=>[$product->id]]) }}">Print barcode / PDF</a></div></div></td><td>{{ $product->supplier }}<small class="d-block">{{ $product->product_code ?: 'No supplier code' }}</small></td><td>{{ $product->categories->pluck('name')->join(', ') }}</td><td>{{ $product->total_selling_price_cad===null?'—':rtrim(rtrim($product->total_selling_price_cad,'0'),'.') }}</td><td>{{ $product->is_active?'Active':'Inactive' }}</td><td><a data-product-modal class="btn btn-sm btn-outline-primary" href="{{ route('admin.products.show',[$product,'modal'=>1]) }}">View</a> @if(auth()->user()->hasAdminPermission('products.manage'))<a data-product-modal class="btn btn-sm btn-outline-primary" href="{{ route('admin.products.edit',[$product,'modal'=>1]) }}">Edit</a>@endif</td></tr>@empty<tr><td colspan="7">No matching products.</td></tr>@endforelse</tbody></table>
@if(auth()->user()->hasAdminPermission('products.manage'))<div class="mmc-filters"><label>Category for selected products<select class="form-control" name="category_id" required><option value="">Choose category</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label>Action<select class="form-control" name="mode"><option value="add">Add category (keep existing)</option><option value="replace">Replace all categories</option></select></label><button class="btn btn-primary">Apply Categories</button><button class="btn btn-outline-primary" type="button" data-print-barcodes="{{ route('admin.products.labels') }}">Print Selected Barcodes</button></div>@endif
{{ $products->links('pagination::bootstrap-4') }}</div></div></div></form>
<dialog id="product-dialog" aria-labelledby="product-dialog-title"><header><h2 id="product-dialog-title" class="h4 mb-0">Product</h2><div class="d-flex align-items-center" style="gap:10px"><button type="button" data-save-product class="btn btn-primary" hidden disabled>Save Product</button><button type="button" data-close-modal class="btn btn-outline-primary" aria-label="Close product modal">Close ×</button></div></header><iframe title="Product details and editor"></iframe></dialog>
<script src="{{ asset('admin-assets/product-modals.js') }}?v={{ filemtime(public_path('admin-assets/product-modals.js')) }}"></script>
<script>
document.querySelector('[data-print-barcodes]')?.addEventListener('click', function () {
    const selected = document.querySelectorAll('input[name="product_ids[]"]:checked');
    if (!selected.length) { alert('Select at least one product to print barcode labels.'); return; }
    const url = new URL(this.dataset.printBarcodes, location.href);
    selected.forEach(input => url.searchParams.append('product_ids[]', input.value));
    window.open(url.href, '_blank', 'noopener');
});
</script>
@endsection